---
- name: play Install Geerlingguy Docker
  hosts: default
  become: true
  vars:
    docker_edition: "ce"
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose: true
    docker_compose_version: "1.26.0"
    docker_compose_path: /usr/local/bin/docker-compose
    docker_apt_release_channel: stable
    docker_apt_arch: amd64
    docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
    docker_apt_ignore_key_error: True
    docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    docker_users:
      - ubuntu

  pre_tasks:
    - name: Add universe repository for focal
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu focal universe
        state: present
      when: ansible_distribution_release == 'focal'
    - name: Install gnupg2
      apt:
        name: gnupg2
        state: present
        update_cache: yes

  roles:
    - geerlingguy.docker

- name: play Install the latest goss
  hosts: default
  become: true
  roles:
    - vantaworks.goss

- name: play Install nginx and wordpress
  hosts: default
  become: true
  vars_files:
    - default.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Install NGINX Package
      apt: name={{ item }} update_cache=yes state=latest
      loop: ["nginx"]

    # Nginx Configuration

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: "0755"

    - name: Sets Nginx conf file
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx

    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx

    # UFW Configuration

    - name: "UFW - Allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp

    - name: "UFW - Allow HTTPS on port {{ https_port }}"
      ufw:
        rule: allow
        port: "{{ https_port }}"
        proto: tcp

    # WordPress

    - name: Download and unpack latest WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/{{ http_host }}"
        remote_src: yes
        creates: "/var/www/{{ http_host }}/wordpress"
      tags: [wordpress]

  # Handlers

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
